export const themeCatalog = [
  { id: "apple-glass-white-default", name: "Apple Glass White (Default)", tags: ["light", "glass", "minimal"] },
  { id: "classic-clean", name: "Classic Clean", tags: ["clean", "neutral"] },
  { id: "minimal-light", name: "Minimal Light", tags: ["light", "minimal"] },
  { id: "minimal-dark", name: "Minimal Dark", tags: ["dark", "minimal"] },
  { id: "neon-arcade", name: "Neon Arcade", tags: ["arcade", "vibrant"] },
  { id: "retro-pixel", name: "Retro Pixel", tags: ["retro", "pixel"] },
  { id: "esports-stage", name: "Esports Stage", tags: ["competitive"] },
  { id: "pastel-pop", name: "Pastel Pop", tags: ["cute", "pastel"] },
  { id: "mono-pro", name: "Mono Pro", tags: ["mono", "clean"] },
  { id: "forest-calm", name: "Forest Calm", tags: ["nature", "calm"] },
  { id: "high-contrast-access", name: "High Contrast Access", tags: ["accessibility"] },
  { id: "paper-zine", name: "Paper Zine", tags: ["editorial"] },
  { id: "cyber-grid", name: "Cyber Grid", tags: ["tech", "dark"] },
  { id: "catstacker-arcade", name: "CatStacker Arcade", tags: ["cat", "cute", "arcade", "art"] },
  { id: "blonde-anime-glow", name: "Blonde Anime Glow", tags: ["anime", "art"] },
  { id: "ocean-depths", name: "Ocean Depths", tags: ["blue", "calm"] },
  { id: "desert-gold", name: "Desert Gold", tags: ["warm"] },
  { id: "noir-detective", name: "Noir Detective", tags: ["dark", "cinematic"] },
  { id: "graffiti-street", name: "Graffiti Street", tags: ["urban", "bold"] },
  { id: "arcane-library", name: "Arcane Library", tags: ["fantasy"] },
  { id: "jungle-ruins", name: "Jungle Ruins", tags: ["nature", "adventure"] },
  { id: "candy-rush", name: "Candy Rush", tags: ["bright", "cute"] },
  { id: "glacier-tech", name: "Glacier Tech", tags: ["tech", "cool"] },
  { id: "volcanic-core", name: "Volcanic Core", tags: ["hot", "dramatic"] },
  { id: "royal-velvet", name: "Royal Velvet", tags: ["luxury"] },
  { id: "synth-sunset", name: "Synth Sunset", tags: ["retro", "vibrant"] },
  { id: "comic-pop", name: "Comic Pop", tags: ["comic", "bold"] },
  { id: "horror-arcade", name: "Horror Arcade", tags: ["horror", "dark"] },
  { id: "zen-garden", name: "Zen Garden", tags: ["calm", "minimal"] },
  { id: "meadow-story", name: "Meadow Story", tags: ["floral", "cozy"] },
  { id: "celestial-shrine", name: "Celestial Shrine", tags: ["mystic"] },
  { id: "mecha-hangar", name: "Mecha Hangar", tags: ["mecha"] },
  { id: "vapor-dream", name: "Vapor Dream", tags: ["vaporwave"] },
  { id: "storybook-fantasy", name: "Storybook Fantasy", tags: ["storybook"] },
  { id: "storm-racer", name: "Storm Racer", tags: ["speed"] },
  { id: "samurai-ink", name: "Samurai Ink", tags: ["ink", "minimal"] },
  { id: "space-opera", name: "Space Opera", tags: ["space"] },
  { id: "chibi-cafe", name: "Chibi Cafe", tags: ["chibi", "cute"] }
];
